# Generated by Django 4.2.4 on 2023-08-06 15:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('src', models.CharField(max_length=100)),
                ('dest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainCabin',
            fields=[
                ('train_cabin_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('train_cabin_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_book.train')),
            ],
        ),
        migrations.CreateModel(
            name='TripSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_booked', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('train_cabin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_book.traincabin')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_book.train')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_book.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TrainCabinClass',
            fields=[
                ('train_cabin_class_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('cabin_class_name', models.CharField(max_length=100)),
                ('fair_price', models.IntegerField()),
                ('train_cabins', models.ManyToManyField(null=True, related_name='train_cabins', to='train_book.traincabin')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='train_cabins',
            field=models.ManyToManyField(null=True, related_name='trains', to='train_book.traincabin'),
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('trip_seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to='train_book.tripseats')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_cost', models.IntegerField()),
                ('passengers', models.ManyToManyField(null=True, related_name='booking', to='train_book.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_book.trip')),
            ],
        ),
    ]
